### ISSUE TITLE
Failing case #4

### ISSUE THREAD

**Issue by zhaonian** [DaviesX/Connect_K_HolographicX#4]
java -jar connectk.jar cpp:bin/HolographicXAI
player1, GUI
Player 1 says:
Player 1 says:
Player 1 returns move 1, 0.
Player 2 says:
Starting process HolographicXAI
outputting: 0 ai pieces 1 human pieces 8 empty pieces
sending command
getting response
got unexpected response: Make sure this program is ran by the Java shell. It is incomplete on its own. 
got unexpected response: **deadline**50000
Player 2 returns move 1, 1.
Player 1 says:
Player 1 returns move 0, 1.
Player 2 says:
outputting: 1 ai pieces 2 human pieces 6 empty pieces
sending command
getting response
got unexpected response: **deadline**50000
Player 2 returns move 0, 0.
Player 1 says:
Player 1 returns move 2, 2.
Player 2 says:
outputting: 2 ai pieces 3 human pieces 4 empty pieces
sending command
getting response
got unexpected response: **deadline**50000
Player 2 returns move 2, 1.
Player 1 says:
Player 1 returns move 1, 2.
Player 2 says:
outputting: 3 ai pieces 4 human pieces 2 empty pieces
sending command
getting response
got unexpected response: **deadline**50000
Player 2 returns move 2, 0.
Player 1 says:
Player 1 returns move 0, 2.
Player 1 (GUI) wins!

**Comment by DaviesX** [comment]
Player 1 returns move 1, 0.
Player 2 returns move 1, 1.
Player 1 returns move 0, 1.
Player 2 returns move 0, 0.
Player 1 returns move 2, 2.
Player 2 returns move 2, 1.
Player 1 returns move 1, 2.
Player 2 returns move 2, 0.
Player 1 returns move 0, 2.

**Comment by DaviesX** [comment]
Cause: goal state and null state should return different value.
Status: Fixed.
